trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: | 
    gcc main.c -Wall -o my_program
  displayName: 'compile'

- script: | 
    ./my_program
  displayName: 'run my_program'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifactName: my_program_build
